function [agentdata, gbest,pbest] = parsePsoData(nagent)

swarmdata = readtable("swarmLog.csv");
psodata = readtable("agent0/psoData.csv");
phasedata = readtable("agent0/phaseData.csv");

for i = 1:(nagent-1)
    psodata = [psodata;readtable(sprintf("agent%d/psoData.csv",i))];
    phasedata = [phasedata;readtable(sprintf("agent%d/phaseData.csv",i))];
end

agentdata = join(psodata,phasedata,'Keys',{'agent','step'});
nvar = width(agentdata);
bestdata = join(swarmdata,agentdata, ...
                'LeftKeys',{'step','histBestAgent'}, ...
                'RightKeys',{'step','agent'}, ...
                'RightVariables',{'agent','step','bestStep'}, ...
                'LeftVariables',{'histBestAgent'});
gbest = join(bestdata,agentdata, ...
    'LeftKeys',{'agent','bestStep'}, ...
    'RightKeys',{'agent','step'}, ...
    'LeftVariables',{'step','histBestAgent','agent','bestStep'}, ...
    'RightVariables',4:nvar);
pbest = join(agentdata,agentdata, ...
    'LeftKeys',{'agent','bestStep'}, ...
    'RightKeys',{'agent','step'}, ...
    'LeftVariables',{'agent','step','bestStep'}, ...
    'RightVariables',4:nvar);